### PR TITLE
Update chre module to revision b062102

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Pull latest changes from ToT.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
@yperess this is a merge of the current chre zephyr repo against the android one... is this the right way of uprevving or is there a better one?

**Review by yperess — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@MaureenHelm can you merge this? (I don't have permissons to add reviewers)

**Comment by fabiobaltieri** [comment]
Just to clarify, this PR includes the merge commit itself, lmk if I should just push the upstream patch and we want to let github handle the merge instead (that's how it works for mcuboot it turns out).

**Review by gmarull — APPROVED** [review]

**Comment by gmarull** [comment]
@carlescufi

**Pull request merged**
