### PR TITLE
Pull latest changes from ToT

### PR DESCRIPTION
**Pull request by yperess**

### CODE REVIEW

**Comment by MaureenHelm** [comment]
`[DO NOT MERGE] Add temporary assertion to detect scan errors` looks suspicious. Is this from upstream?

**Comment by yperess** [comment]
> `[DO NOT MERGE] Add temporary assertion to detect scan errors` looks suspicious. Is this from upstream?

https://android.googlesource.com/platform/system/chre/+log#:~:text=ad9e4ac-,%5BDO%20NOT%20MERGE%5D%20Add%20temporary%20assertion%20to%20detect%20scan%20errors,-by%20Arthur%20Ishiguro

**Comment by yperess** [comment]
Looks like Android finished pushing their latest release to the public git so this is the latest pull from `upstream/master`

**Comment by MaureenHelm** [comment]
> Looks like Android finished pushing their latest release to the public git so this is the latest pull from `upstream/master`

Great, thanks. Will you please update `west.yml` in zephyrproject-rtos/zephyr#41735 to reference this PR, so we can get a CI build with it?

**Comment by yperess** [comment]
> > Looks like Android finished pushing their latest release to the public git so this is the latest pull from `upstream/master`
> 
> Great, thanks. Will you please update `west.yml` in [zephyrproject-rtos/zephyr#41735](https://github.com/zephyrproject-rtos/zephyr/pull/41735) to reference this PR, so we can get a CI build with it?

Done https://github.com/zephyrproject-rtos/zephyr/pull/41735

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
